# Welcome to Jekyll!

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
remote_theme: chrisrhymes/bulma-clean-theme


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: en
title: DevPika's Corner
tagline: Welcome to Ayaskant Panigrahi's personal website!
email: ayaskant.panigrahi@gmail.com
description: >
  Welcome to Ayaskant Panigrahi's personal website!
baseurl: ""
url: ""
permalink: pretty
# gh_sponsor: chrisrhymes
#hide_share_buttons: true
theme_color: '#eeeeee'
hide_share_buttons: true
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

# Site Author
author:
  name             : "Ayaskant Panigrahi"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Hopelessly in love with clean code and unobtrusive design!"
  affiliation      : "MSc at SIAT, Simon Fraser University"
  location         : "Vancouver"
  email            : "ayaskant.panigrahi@gmail.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DevPika"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ayaskant-panigrahi"
    - label: "Behance"
      icon: "fab fa-fw fa-behance-square"
      url: "https://www.behance.net/ayaskant"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
  github: DevPika

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"

# Disqus Comments
# disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  # shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from

include:
  - _pages
  - _posts

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ignore/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
    values:
      show_sidebar: true
      menubar: side_menu
      hide_hero: false
      hero_height: "is-small"
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Ayaskant Panigrahi"
      layout: post
      excerpt_separator: <!--more-->
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: project

markdown: kramdown
highlighter: rouge

footer_menu: example_footer_menu

collections:
  projects: 
    output: true
    layout: default
    image: https://via.placeholder.com/800x600
    show_sidebar: true