# Welcome to Jekyll!

# Build settings
# theme: minima
# plugins:
#   - jekyll-feed
remote_theme: chrisrhymes/bulma-clean-theme


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: en
title: DevPika's Corner
tagline: Welcome to Ayaskant Panigrahi's personal website!
email: ayaskant.panigrahi@gmail.com
description: >
  Welcome to Ayaskant Panigrahi's personal website!
baseurl: ""
url: ""
permalink: pretty
# gh_sponsor: chrisrhymes
#hide_share_buttons: true
theme_color: '#eeeeee'
hide_share_buttons: true
#fixed_navbar: top
#direction: one of <ltr, rtl, auto>, default: ltr

# Site Author
author:
  name             : "Ayaskant Panigrahi"
  avatar           : "/assets/images/bio-photo.jpg"
  bio              : "Hopelessly in love with clean code and unobtrusive design!"
  affiliation      : "MSc at SIAT, Simon Fraser University"
  location         : "Vancouver"
  email            : "ayaskant.panigrahi@gmail.com"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/devpika"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/DevPika"
    - label: "Glitch"
      url: "https://glitch.com/@gameshire"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ayaskant"
    - label: "itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://gameshire98.itch.io/"
    - label: "Behance"
      icon: "fab fa-fw fa-behance-square"
      url: "https://www.behance.net/ayaskant"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:
  github: DevPika

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  collection: 'posts'
  per_page: 5

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  # tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

  # Optional, the default file extension for generated pages (e.g html, json, xml).
  # Internally this is set to html by default
  extension: html

  # Optional, the default name of the index file for generated pages (e.g. 'index.html')
  # Without file extension
  # indexpage: 'index'

############################################################

# Disqus Comments
# disqus:
  # Leave shortname blank to disable comments site-wide.
  # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
  # shortname: my_disqus_shortname
  # shortname: csrhymes


plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-redirect-from
  - jekyll-remote-theme

include:
  - _pages
  - _posts

exclude: 
  - Gemfile
  - clean-theme.gemspec
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ignore/

livereload: true

sass:
  style: compressed
  source_dir: _sass

#google_analytics: UA-code-here

defaults:
  -
    scope:
      path: ""
    values:
      show_sidebar: true
      menubar: side_menu
      hide_hero: false
      hero_height: "is-small"
  -
    scope:
      path: ""
      type: "posts"
    values:
      timeline-type: "Posts"
      author: "Ayaskant Panigrahi"
      layout: post
      excerpt_separator: <!--more-->
  -
    scope:
      path: ""
      type: "projects"
    values:
      timeline-type: "Projects"
      layout: project
  -
    scope:
      path: ""
      type: "education"
    values:
      timeline-type: "Education"
      layout: stub
  -
    scope:
      path: ""
      type: "experience"
    values:
      timeline-type: "Experience"
      layout: stub
  -
    scope:
      path: ""
      type: "publications"
    values:
      timeline-type: "Publications"
      layout: stub
  -
    scope:
      path: ""
      type: "coursework"
    values:
      timeline-type: "Coursework"
      layout: stub
  -
    scope:
      path: ""
      type: "achievements"
    values:
      timeline-type: "Achievements"
      layout: stub

markdown: kramdown
highlighter: rouge

# footer_menu: example_footer_menu

collections:
  projects: 
    output: true
    layout: default
    image: https://via.placeholder.com/800x600
    show_sidebar: true
  education:
    output: true
    layout: default
    show_sidebar: true
  experience:
    output: true
    layout: default
    show_sidebar: true
  publications:
    output: true
    layout: default
    show_sidebar: true
  coursework:
    output: true
    layout: default
    show_sidebar: true
  achievements:
    output: true
    layout: default
    show_sidebar: true
